services:
  postgres:
    image: postgres:16-alpine
    container_name: impulse-bot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: impulse_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bot:
    build: .
    container_name: impulse-bot
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: impulse_bot
    env_file:
      - .env
    # volumes:
    #   - ./credentials.json:/app/credentials.json:ro
    #   - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data: